install: mac
	/usr/bin/install -m 644 dot-gitrc ~/.gitrc

mac:
	/usr/bin/install -m 644 ../vendor/github/gitignore/Global/macOS.gitignore ~/.gitignore

win:
	/usr/bin/install -m 644 ../vendor/github/gitignore/Global/Windows.gitignore ~/.gitignore
